### ISSUE TITLE
Data file didnt have Test_1.csv ?where can  i  get it ?

### ISSUE THREAD

**Issue by doube1008** [laiadc/PFM_Bearing_Fault_Detection#1]

**Comment by laiadc** [comment]
The file was too large to upload in GitHub. The IMS dataset is publicly available at 
https://ti.arc.nasa.gov/tech/dash/groups/pcoe/prognostic-data-repository/#bearing
It's the fourth data set (Bearing Data Set). You can download a .zip file containing all the tests.

**Comment by doube1008** [comment]
i had download data set   How should I use this data   What should I do? Change the decompressed file to .csv format
